{
 "title": "Home",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device Id",
    "query": "SELECT distinct(\"deviceId\") FROM \"data_allpa\""
   }
  ]
 },
 "panels": [
  { "title": "Available Devices", "type": "dashlist", "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 } },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 } },
  { "title": "PWOne Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Environment Temperature",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Environment Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"Temperature\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "environmentTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Environment Humidity",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"Humidity\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "environmentHumidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"RTD\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "internalTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"pH\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "soilMoisture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DO",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"DO\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "soilMoisture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "EC",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "μS/cm " } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"EC\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "internalTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Flow",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Liters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_allpa",
     "query": "SELECT \"Liters\" FROM \"data_pwo\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "lightIntensity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}